---
collections:
  # Required for debops
  - name: ansible.netcommon
  # DebOps for base system management
  - name: debops.debops
    version: "3.1.0"
  # For managing resources in Openstack API compatible clouds
  - name: openstack.cloud
    version: ">=2.0.0"
  # For managing resources at Vultr
  - name: vultr.cloud
    version: ">=1.5.0"
  # Misc resources
  - name: community.general
  # Used for managing grafana resources
  - name: grafana.grafana
    version: ">=2.0.1"
  # To interact with IPAM
  - name: netbox.netbox
  # For AWS management
  - name: amazon.aws

roles:
  - name: medeopolis.debops-gpgkey
    src: https://github.com/medeopolis/debops-gpgkey.git
    type: git
  - name: medeopolis.debops-duply
    src: https://github.com/medeopolis/debops-duply.git
    type: git

