---
# (C) 2023 Medeopolis. Karl Goetz <karl+ansible@medeopolis.au>

# -e current_openstack_cloud=ovh-test

- name: Test connection to OpenStack API
  hosts: localhost
  tasks:
    # This creates/populates openstack.clouds variable
    # Because only one cloud is being requested openstack.clouds will be a list
    # with one dictionary inside it.
    - name: Access configuration for current cloud
      openstack.cloud.config:
        clouds:
          - "{{ current_openstack_cloud }}"

    - name: Authenticate to cloud
      openstack.cloud.auth:
        cloud: "{{ current_openstack_cloud }}"
      # Returns auth_token; not sure what to do with it though - swift?

    - name: Display auth token
      debug:
        var: auth_token

    # FIXME: doesn't appear to be pulling any config
#     - name: Gather information about connecting user
#       openstack.cloud.identity_user_info:
#         cloud: "{{ current_openstack_cloud }}"
#         # filters
#         name: "openstack.clouds.0.auth.username }}"
#
#     - name: Gather projects of connecting user
#       openstack.cloud.project_info:
#         cloud: "{{ current_openstack_cloud }}"
#         filters:
#           # enabled: true
#       register: os_project_list
#
#     - debug:
#         var: os_project_list

    - name: List servers in project {{ openstack.clouds.0.auth.project_name }} on cloud {{ current_openstack_cloud }}
      openstack.cloud.server_info:
        cloud: "{{ current_openstack_cloud }}"
      register: openstack_server_list

    - name: Count list of servers
      debug:
        # var: openstack_server_list.openstack_servers
        msg: "There are {{ openstack_server_list.openstack_servers | length }} servers in this project"

