---
# (C) 2023 Medeopolis. Karl Goetz <karl+ansible@medeopolis.au>

# Check if we're able to access the Vultr API endpoint

# vultr_api_key must be set in inventory.

- name: Test connection to Vultr API within Ansible
  hosts: localhost
  tasks:
    - name: Look up account information
      vultr.cloud.account_info:
        api_key: "{{ vultr_api_key }}"
      register: result
    - name: Output account information
      debug:
        msg: "{{ result }}"

