---
# Your OpenStack (and Ansible) configuration is correct if this returns
# information about your hosts.

- name: Test Ansible and BinaryLane are talking
  hosts: localhost
  tasks:
    - name: Check server information
      openstack.cloud.server_info:
        all_projects: true
        cloud: binarylane
      register: result
    - name: Output server information
      debug:
        msg: "{{ result.openstack_servers }}"

