---
# Check if we're able to access the Vultr API endpoint

- name: Test connection to Vultr API within Ansible
  hosts: localhost
  tasks:
    - name: Look up account information
      vultr.cloud.account_info:
        api_key: "{{ vultr_api_key }}"
      register: result
    - name: Output account information
      debug:
        msg: "{{ result }}"

