---
# (C) 2023 Medeopolis. Karl Goetz <karl+ansible@medeopolis.au>

- name: Deploy Ansible Semaphore UI
  hosts: semaphore_servers
  roles:
    - debops.debops.nginx
    - debops.debops.ferm
    - semaphore

