---

# Things which are applied on all systems we manage - our baseline

- name: Pre-DebOps configuration changes
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Check if UFW is installed
      stat:
        path: /usr/sbin/ufw
        get_attributes: false
        get_checksum: false
        get_mime: false
      register: ufw_stat
    - name: Permit access through UFW on port 80 (for Lets Encrypt)
      community.general.ufw:
        rule: allow
        comment: "Access to web ports for Lets Encrypt"
        port: 80
        proto: tcp
      # Only web servers need these ports open.
      when:
        - "'debops_service_nginx' in group_names"
        - ufw_stat.stat.exists
      # TODO: Catch when "Status: inactive" is returned by ufw. Might need a reboot to resolve that?

# NOTE: Playbook imports have to sit at the top level.
- name: Run DebOps common.yaml
  ansible.builtin.import_playbook: debops.debops.common

- name: Run DebOps Fail2ban
  ansible.builtin.import_playbook: debops.debops.service.fail2ban

# TODO: if auditd rules were changed restart the service
# Will have to check for file at start and finish then restart if its changed.

